Gen a C prg and check its GCC flags as well

diff --git a/show_gcc_switches b/show_gcc_switches
--- a/show_gcc_switches
+++ b/show_gcc_switches
@@ -32,6 +32,7 @@ show_gcc_def_options()
 {
 [[ $# -eq 1 ]] && local LOG=$1 || LOG=${REPORT_GCC_DEF_OPTIONS}
 
+# Generate a C 'Hello, world', compile it with -g and figure out the GCC option switches
 cat > .hello.c <<@EOF@
 #include <stdio.h>
 #include <unistd.h>
@@ -40,11 +41,18 @@ int main()
 	printf("Hello, world\n");
 }
 @EOF@
-gcc .hello.c >/dev/null 2>&1 || die "gcc failed"
-gcc -Q -v .hello.c 2> ${LOG}
-rm -f .hello.c a.out
+gcc -g .hello.c -o .a.out >/dev/null 2>&1 || {
+	echo "gcc failed" ; return
+}
 echo "
-GCC : generic: default options report written to: ${LOG}"
+Ordinary C program compiled with -g:"
+show_gcc_option_switches ./.a.out
+rm -f .hello.c .a.out
+
+# Other detailed method of getting compiler info : -Q -v
+gcc -Q -v .hello.c 2> ${LOG}
+echo "
+GCC : generic: default options detailed report written to: ${LOG}"
 }
 
 show_gcc_def_optimization_options()
@@ -61,7 +69,7 @@ echo "GCC : generic: all disabled optimizations (${num_opt_dis})"
 [[ ${num_opt_dis} -gt 0 ]] && {
  gcc -Q --help=optimizers |grep " \-f.*\[disabled\]$" >> ${LOG}
 }
-echo "GCC : generic: default optimization options report written to: ${LOG}"
+echo "GCC : generic: default optimization options detailed report written to: ${LOG}"
 }
 
 show_gcc_option_switches()
@@ -80,7 +88,7 @@ file $1 |grep "with debug_info" >/dev/null
 }
 set -e
 #GCC_VER=$(gcc -v 2>&1 |tail -n1 |awk '{print $3}')
-echo "$1:"
+echo "$1: GCC option switches passed, summary report:"
 # On embedded, readelf can spit out errors + a lot of matches to 'producer' + many repititions;
 # also, the gcc ver doesn't seem to match here.
 # So trim the o/p and 'unique' it (eliminate dups) via sort -u !
