detect whether man gcc works at all

diff --git a/show_gcc/show_gcc_switches b/show_gcc/show_gcc_switches
--- a/show_gcc/show_gcc_switches
+++ b/show_gcc/show_gcc_switches
@@ -195,9 +195,17 @@ do
 			SHOW_GCC_DEF_OPTIMIZATION_OPTIONS=1
 			;;
 		  m)
-			SHOW_GCC_MANPAGE_SNIPPET=1
-			man gcc |col -b > mangcc
-			GCC_MANPAGE_FILE=mangcc
+		        set +e
+		        man gcc >/dev/null 2>&1
+			if [[ $? -ne 0 ]] ; then
+			  SHOW_GCC_MANPAGE_SNIPPET=0
+			  echo "'man gcc' not working, aborting man page snippets facility"
+			else
+			  SHOW_GCC_MANPAGE_SNIPPET=1
+			  man gcc |col -b > mangcc
+			  GCC_MANPAGE_FILE=mangcc
+			fi
+		        set -e
 			;;
 		  h|H|?)
 		    usage
